### ISSUE TITLE
Fixing up the get_average_length_function

### ISSUE THREAD

**Issue by jmcrey** [sudhakarpadhilahouse/pwp-capstones#1]
```
def get_average_sentence_length(text):
    cleantext=text.replace("?", ".")
    cleantext1=cleantext.replace(",", ".")    
    cleantext2=cleantext1.replace("'", "")
    cleantext3=cleantext2.replace("\"", "")     
    cleanertext=cleantext3.replace("!", ".")    
    sentences_in_text=cleanertext.split(".")
    sentences_number=len(sentences_in_text)-1    
    words_length=0
    for sentence in sentences_in_text:
        word_in_sentences=sentence.split(" ")
        words_length = words_length + len(word_in_sentences)-1
    average_sentence_length=words_length/sentences_number    
    return average_sentence_length
```

This is super close to being correct! The code is just doing a little bit too much in order for the average sentence length to be calculated correctly. 

First, I just wanted to say that those replace statements are excellently implemented. However, we actually only need to replace the extraneous punctuation (e.g. end of sentence punctuation) with a period. So, instead of replacing quotes, backslashes and commas, we actually just want to replace question marks and exclamation points. With this in mind, we would just be left with:

```
cleantext=text.replace("?", ".")
cleanertext=cleantext.replace("!", ".") 
sentences_in_text=cleanertext.split(".")
```

Now, when our code splits, we can be certain that it is only splitting up by sentences and not by half sentences. Before, we were also splitting by commas, which is problematic because that doesn't indicate the end of the sentence. Really, if we just removed the line where we changed the commas into a period, our code would have calculated each of the averages correctly. So, overall very nice job! Super close to being 100% correct.

**Comment by sudhakarpadhilahouse** [comment]
updating the code and will submit as murder_mystery_fixed.ipynb after updating the 3 reported issues
