### ISSUE TITLE
So close on the build_frequency_table function!

### ISSUE THREAD

**Issue by jmcrey** [sudhakarpadhilahouse/pwp-capstones#2]
```
def build_frequency_table(corpus):
    frequency_table={}
    for word in corpus:
        count=1        
        if word in frequency_table:
            count+=1
            frequency_table[word]=count
        else:
            frequency_table[word]=count
    return frequency_table
```

This is super close to being correct; we just need to make one minor change.

Instead of declaring `count` in the beginning of our function, we actually would want to declare it after the `else` clause. Then, we would assign `count` to the `frequency_table[word]` like we have now. Of course, we could always just assign `frequency_table[word]` to equal 1; but, either way will work just fine!

Then, for the words that are already in the frequency table (e.g. directly under the `if` statement), we actually just want to make a statement like so:

`frequency_table[word] += 1`

This is because we want to update what's already inside the frequency_table instead of just adding one to one. 

If we do it the previous way, the maximum number that is going to be counted is two. This is because `count+=1` can only ever be two when we have `count = 1` directly before that. For example, if our function were to encounter a list like this: `['where', 'we',  'have', 'the', 'birds', 'that', 'have', 'the', 'penguins', 'that', 'have', 'the', 'eggs']`, our function would output: 

```{'birds': 1, 'eggs': 1, 'have': 2, 'penguins': 1, 'that': 2, 'the': 2, 'we': 1, 'where': 1}```

So, by just moving that and updating what's already there, we are given the correct results. Here is the final correct code:

```
def build_frequency_table(corpus):
    frequency_table={}
    for word in corpus:        
        if word in frequency_table:
            frequency_table[word]+=count
        else:
            count=1
            frequency_table[word]=count
    return frequency_table
```

**Comment by sudhakarpadhilahouse** [comment]
thanks for the feedback, i agree there was an issue when testing with different input data, thanks, i will update the file as murder_mystery_fixed.ipynb
