### ISSUE TITLE
One little thing about frequency_comparison

### ISSUE THREAD

**Issue by jmcrey** [sudhakarpadhilahouse/pwp-capstones#3]
`frequency_count=len(mutual_appearances)/len(appearances)`

This function is super close to being 100% correct. The one thing we have to change is actually our calculation of our `frequency_comparison` variable. Instead of using `len()`, we would actually need to use `sum()`. `sum()` adds up all the values in a list of integers and returns the sum of those values. 

So, the reason why we want to use `sum` instead of `len` is because not all values in our [cleverly generated] list are going to be 1. Some may be two, three, four, etc. depending on how many of one word is found. But, when we use the `len()` function, we are only counting how many values there are inside the list (not adding up all the values in the list). Essentially, we are missing those values that are more than one in our frequency comparison. 

However, once we switch to using `sum()` , we can correct for that and get the correct comparison. Here is our corrected line:

`frequency_count=sum(mutual_appearances)/sum(appearances)`

As a side note, we don't actually need the last two `for` loops in our function since we are not returning the `frequency_sum` variable. So, essentially our function would just be left with this:

```

def frequency_comparison (table1,table2):
    appearances = []
    mutual_appearances = []
    for key, value in table1.items():        
        if key in table2:
            table2value=table2.get(key)            
            if value<table2value:
                appearances.append(table2value)                        
                mutual_appearances.append(value)                                       
            else:
                appearances.append(value)                        
                mutual_appearances.append(table2value)                
        else:
            appearances.append(value)
    for key,value in table2.items():
        if key not in table1:
            appearances.append(value)
    frequency_count=len(mutual_appearances)/len(appearances)
    return frequency_count
```

But that's less important since none of those `for` loops were effecting our output (just the performance since `for` loops can take time to complete). Just a note!

**Comment by sudhakarpadhilahouse** [comment]
thanks, i was confused whether to use length or sum hence i wrote both but couldn't identify which is best suited. so i corrected the code and now will upload as murder_mystery_fixed.ipynb
