### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jmcrey** [sudhakarpadhilahouse/pwp-capstones#4]
## Rubric Score
 
### Criteria 1: Valid Python Code
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Code runs without any errors.
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Code produces 100% of required functions and classes and calls them in an appropriate order. Notably, the functions were a little bit "out-of-order" from what the project intended, but each function was invoked correctly. Very nice job calling them in the appropriate order (especially in the `TextSample` class!).
 
### Criteria 3: Software Architecture
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Code is separated into distinct classes and functions each which are invoked for their own purposes. 
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 3 (Meets Expectations)
* _Comment(s):_ Python language features are usually used, but there are 1-3 cases of a coded construction could have been accomplished by a Python builtin. Really, the biggest example of this was that we should have used the `sum` instead of `len` list feature in our frequency comparison (as noted in [this issue](https://github.com/sudhakarpadhilahouse/pwp-capstones/issues/3))

### Criteria 5: Produces Accurate Output
* _Score Level:_ 2 (Approaches Expectations)
* _Comment(s):_ The code output is incorrect. We had just a few small errors in our code which prevented 100% accurate output; but, each of our functions were on the right track. They only required a few small modifications in order to generate the right output 
 
### Overall Score: 17/20
Overall, this project was a solid python code base. Each of the functions were either implemented completely correctly, or only required a few small code changes in order to be 100% correct. The small things are the hardest to catch! I would recommend trying to test out each function before moving onto the next one, and test it using something weird. For example, when I tested the `build_frequency_table` function, I gave it a very weird case of having 3 words in one sentence. If we just take the time to do one "edge case" test, it can really highlight what small bugs we have in our code and push them to be 100% correct. 

Some smaller things are to be more generous about using spacing and using underscores in our naming conventions. For instance, in our function `find_text_similarity`, instead of naming the variable `textsample1`, we can name it `text_sample_1` in order for it to be easier to read. Or, when calculating `similarity_score`, we can use spacing between the parentheses to ease the clutter on the screen:

`similarity_score=( sentence_lenth_similarity + word_count_similarity + ngram_similarity ) / 3`

But, these are just small changes that are primarily aimed to enhance readability. 

Overall, this was a great project. Nice job!

**Comment by sudhakarpadhilahouse** [comment]
uploading the updated file as murder_mystery_fixed.ipynb
